import turtle
# # turtle.forward(150)
# # turtle.right(90)
# # turtle.forward(150)
turtle.speed(0)
# screen = turtle.getscreen()
# screen.bgcolor('light blue')
def rectangle(x, y):
  turtle.pendown()
  turtle.left(90)
  turtle.forward(x)
  turtle.left(90)
  turtle.forward(y)
  turtle.left(90)
  turtle.forward(x)
  turtle.left(90)
  turtle.forward(y)
  turtle.penup()
def window(x, y):
  turtle.goto(x, y)
  turtle.pendown()
  turtle.fillcolor('white')
  turtle.begin_fill()
  rectangle(60, 50)
  turtle.end_fill()
  turtle.goto(x, y)
  rectangle(10, 20)
  turtle.goto(x + 10, y)
  rectangle(10, 20)
  turtle.goto(x + 20, y)
  rectangle(10, 20)
  turtle.goto(x + 30, y)
  rectangle(10, 20)
  turtle.goto(x + 40, y)
  rectangle(10, 20)
  turtle.goto(x + 50, y)
  rectangle(10, 20)
  turtle.end_fill()
  turtle.penup()
# # Sky
# screen = turtle.getscreen()
# screen.bgcolor('light blue')
# # Building
# turtle.goto(0, 0)
# turtle.speed(0)
# turtle.fillcolor('maroon')
# turtle.begin_fill()
# turtle.shape("arrow")
# turtle.forward(200)
# turtle.right(90)
# turtle.forward(200)
# turtle.right(90)
# turtle.forward(200)
# turtle.right(90)
# turtle.forward(200)
# turtle.right(90)
# turtle.end_fill()
# turtle.penup()
# #___________________________________________________________________
# turtle.fillcolor('gray')
# turtle.begin_fill()
# turtle.goto(0, 0)
# #turtle.right(90)
# turtle.forward(200)
# turtle.left(135)
# turtle.forward(50)
# turtle.left(45)
# turtle.forward(130)
# turtle.left(45)
# turtle.forward(50)
# turtle.end_fill()
# turtle.right(135)
# turtle.penup()
# # turtle.begin_fill()
# # turtle.left(45)
# # turtle.forward(50)
# # turtle.right(45)
# # turtle.forward(130)
# # turtle.right(45)
# # turtle.forward(50)
# # turtle.backward(50)
# # turtle.left(225)
# # turtle.forward(15)
# # turtle.right(90)
# # turtle.forward(30)
# # turtle.left(90)
# # turtle.forward(20)
# # turtle.left(90)
# # turtle.forward(30)
# # turtle.penup()
# # turtle.goto(125, -200)
# # turtle.pendown()
# # turtle.left(180)
# # turtle.forward(50)
# # turtle.penup()
# # turtle.goto(75, -200)
# # Door
# turtle.penup()
# turtle.goto(75, -200)
# turtle.pendown()
# turtle.fillcolor('white')
# turtle.begin_fill()
# turtle.forward(50)
# turtle.backward(40)
# turtle.right(90)
# turtle.forward(50)
# turtle.left(180)
# turtle.forward(10)
# turtle.right(90)
# turtle.forward(50)
# turtle.left(90)
# turtle.forward(30)
# turtle.left(90)
# turtle.forward(50)
# turtle.backward(25)
# turtle.end_fill()
# turtle.fillcolor('black')
# turtle.begin_fill()
# turtle.circle(5)
# turtle.end_fill()
# turtle.fillcolor('maroon')
# turtle.begin_fill()
# turtle.forward(25)
# turtle.right(90)
# turtle.forward(10)
# turtle.goto(85, -175)
# turtle.end_fill()
# turtle.penup()
# turtle.goto(0, 0)
# turtle.backward(200)
# turtle.pendown()
# turtle.right(45)
# turtle.forward(50)
# turtle.left(45)
# turtle.forward(15)
# turtle.fillcolor('black')
# turtle.begin_fill()
# turtle.right(90)
# turtle.forward(30)
# turtle.left(90)
# turtle.forward(20)
# turtle.left(90)
# turtle.forward(30)
# turtle.penup()
# turtle.end_fill()
# turtle.penup()
# #___________________________________________________________________
# # Bottomleft window
# window(10, -190)
# # turtle.goto(10, -190)
# # turtle.pendown()
# # turtle.fillcolor('white')
# # turtle.begin_fill()
# # rectangle(60, 50)
# # turtle.end_fill()
# # turtle.goto(10, -190)
# # rectangle(10, 20)
# # turtle.goto(20, -190)
# # rectangle(10, 20)
# # turtle.goto(30, -190)
# # rectangle(10, 20)
# # turtle.goto(40, -190)
# # rectangle(10, 20)
# # turtle.goto(50, -190)
# # rectangle(10, 20)
# # turtle.goto(60, -190)
# # rectangle(10, 20)
# # turtle.penup()
# #___________________________________________________________________
# # Bottomright window
# window(190 - 60, -190)
# # turtle.goto(190, -190)
# # turtle.pendown()
# # turtle.fillcolor('white')
# # turtle.begin_fill()
# # rectangle(60, 50)
# # turtle.end_fill()
# # turtle.goto(190, -190)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # turtle.penup()
# # Topright window
# #___________________________________________________________________
# window(190 - 60, -70)
# # turtle.goto(190, -70)
# # turtle.pendown()
# # turtle.fillcolor('white')
# # turtle.begin_fill()
# # rectangle(60, 50)
# # turtle.end_fill()
# # turtle.goto(190, -70)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # turtle.penup()
# #___________________________________________________________________
# # Topleft window
# window(10, -70)
# # turtle.goto(10, -70)
# # turtle.pendown()
# # turtle.fillcolor('white')
# # turtle.begin_fill()
# # rectangle(60, 50)
# # turtle.end_fill()
# # turtle.goto(10, -70)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # turtle.penup()
# # Midright window
# #___________________________________________________________________
# window(130, -130)
# # turtle.goto(190, -130)
# # turtle.pendown()
# # turtle.fillcolor('white')
# # turtle.begin_fill()
# # rectangle(60, 50)
# # turtle.end_fill()
# # turtle.goto(190, -130)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # turtle.penup()
# #___________________________________________________________________
# # Midleft window
# window(10, -130)
# # turtle.goto(10, -130)
# # turtle.pendown()
# # turtle.fillcolor('white')
# # turtle.begin_fill()
# # rectangle(10,-130)
# # turtle.end_fill()
# # turtle.goto(10, -130)
# # rectangle(10, 20)
# # turtle.forward(10)
# # rectangle(10, 20)
# # turtle.forward(10)
# # rectangle(10, 20)
# # turtle.forward(10)
# # rectangle(10, 20)
# # turtle.forward(10)
# # rectangle(10, 20)
# # turtle.forward(10)
# # rectangle(10, 20)
# # rectangle(10, 20)
# # turtle.penup()
# #___________________________________________________________________
# # Road
# turtle.penup()
# turtle.goto(-1000, -1000)
# turtle.fillcolor('dark gray')
# turtle.begin_fill()
# rectangle(2000, 800)
# turtle.end_fill()
#___________________________________________________________________
# turtle.right(144)
# turtle.forward(200)
# turtle.right(144)
# turtle.forward(200)
# turtle.right(144)
# turtle.forward(200)
# turtle.right(144)
# turtle.forward(200)
# turtle.right(144)
# turtle.forward(200)
#___________________________________________________________________
# Weird Dodecahedron:
# count = 0
# while count <6:
#   turtle.right(10)
#   turtle.forward(50)
#   count = count + 1
# turtle.right(120)
# count = 0
# while count <6:
#   turtle.right(10)
#   turtle.forward(50)
#   count = count + 1
#___________________________________________________________________
# Lab 2
#___________________________________________________________________
# House Outline
x = 0
y = x+x
for p in range(5):  
  print(x)
  turtle.left(90)
  turtle.forward(150)
  turtle.right(90)
  turtle.forward(75)
  turtle.right(90)
  turtle.forward(150)
  turtle.right(90)
  turtle.forward(75)
# Left Windows
  turtle.backward(5)
  turtle.right(90)
  turtle.forward(5)
#___________________________________________________________________
  for i in range(3):
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(35)
    turtle.backward(5)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.backward(5)
    turtle.right(90)
    turtle.forward(15)
    turtle.backward(15)
    turtle.left(90)
    turtle.forward(5)
    turtle.penup()
    turtle.forward(45)
    turtle.pendown()
  turtle.penup()
  turtle.home()
  turtle.forward(x)
  turtle.forward(55)
  turtle.left(90)
  turtle.forward(5)
  turtle.pendown()
  for z in range(3):
    print(x)
    print('z = ', z)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(35)
    turtle.backward(5)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.backward(5)
    turtle.right(90)
    turtle.forward(15)
    turtle.backward(15)
    turtle.left(90)
    turtle.forward(5)
    turtle.penup()
    turtle.forward(45)
    turtle.pendown()
  turtle.penup()
  turtle.home()
  turtle.forward(x)
  turtle.left(90)
  turtle.forward(140)
  turtle.pendown()
  turtle.right(90)
  turtle.forward(75)
  turtle.left(90)
  turtle.forward(3)
  turtle.left(90)
  turtle.forward(75)
  for m in range(15):
    for i in range(4):
      turtle.right(90)
      turtle.forward(5)
    turtle.backward(5)
  turtle.penup()
  turtle.home()
  turtle.forward(x)
  turtle.forward(30)
  turtle.pendown()
  turtle.left(90)  
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(15)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(15)
  turtle.right(90)
  turtle.forward(7.5)
  turtle.right(90)
  turtle.circle(2.5)
  x = x + 75
  turtle.penup()
  turtle.home()
  turtle.forward(x)
  turtle.pendown()
  print(x)
